language: python

sudo: required
dist: trusty

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
      - libxml2-dev

install:
  - pip install -r requirements.txt
  - pip install pep8
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs pep8 --ignore=E501
